sudo: false
language: generic
env:
  global:
    - CURL="curl -fsSkL --retry 9 --retry-delay 9"
  matrix:
    - EMACS_VERSION=25.3
    - EMACS_VERSION=26.3

install:
  - $CURL -O https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${EMACS_VERSION}.tar.gz
  - tar -xaf emacs-bin-${EMACS_VERSION}.tar.gz -C /
  - export EMACS=/tmp/emacs/bin/emacs
  - $EMACS --version

script:
  - emacs=$EMACS make update
  - emacs=$EMACS make clean
  - emacs=$EMACS make compile
  - emacs=$EMACS make package-lint
  - emacs=$EMACS make checkdoc
  - emacs=$EMACS make test
